// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: activity.sql

package store

import (
	"context"
)

const createActivity = `-- name: CreateActivity :one
INSERT INTO activity (id, node_id, actor, kind, data, created_at)
VALUES (?, ?, ?, ?, ?, ?)
RETURNING id, node_id, actor, kind, data, created_at
`

type CreateActivityParams struct {
	ID        string
	NodeID    string
	Actor     string
	Kind      string
	Data      string
	CreatedAt string
}

func (q *Queries) CreateActivity(ctx context.Context, arg CreateActivityParams) (Activity, error) {
	row := q.db.QueryRowContext(ctx, createActivity,
		arg.ID,
		arg.NodeID,
		arg.Actor,
		arg.Kind,
		arg.Data,
		arg.CreatedAt,
	)
	var i Activity
	err := row.Scan(
		&i.ID,
		&i.NodeID,
		&i.Actor,
		&i.Kind,
		&i.Data,
		&i.CreatedAt,
	)
	return i, err
}

const deleteActivityForNode = `-- name: DeleteActivityForNode :exec
DELETE FROM activity WHERE node_id = ?
`

// All timeline entries of a node -- cleaned when the node is deleted.
func (q *Queries) DeleteActivityForNode(ctx context.Context, nodeID string) error {
	_, err := q.db.ExecContext(ctx, deleteActivityForNode, nodeID)
	return err
}

const listActivity = `-- name: ListActivity :many
SELECT id, node_id, actor, kind, data, created_at FROM activity WHERE node_id = ? ORDER BY created_at, id
`

// Typed timeline of a node, oldest first (chronological read).
func (q *Queries) ListActivity(ctx context.Context, nodeID string) ([]Activity, error) {
	rows, err := q.db.QueryContext(ctx, listActivity, nodeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Activity
	for rows.Next() {
		var i Activity
		if err := rows.Scan(
			&i.ID,
			&i.NodeID,
			&i.Actor,
			&i.Kind,
			&i.Data,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
