// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: groups.sql

package store

import (
	"context"
	"database/sql"
)

const countChildGroups = `-- name: CountChildGroups :one
SELECT COUNT(*) FROM groups WHERE parent_id = ?
`

func (q *Queries) CountChildGroups(ctx context.Context, parentID sql.NullString) (int64, error) {
	row := q.db.QueryRowContext(ctx, countChildGroups, parentID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countGroupWorkspaces = `-- name: CountGroupWorkspaces :one
SELECT COUNT(*) FROM workspaces WHERE group_id = ?
`

func (q *Queries) CountGroupWorkspaces(ctx context.Context, groupID sql.NullString) (int64, error) {
	row := q.db.QueryRowContext(ctx, countGroupWorkspaces, groupID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createGroup = `-- name: CreateGroup :one
INSERT INTO groups (id, name, parent_id, ord, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?)
RETURNING id, name, parent_id, ord, created_at, updated_at
`

type CreateGroupParams struct {
	ID        string
	Name      string
	ParentID  sql.NullString
	Ord       string
	CreatedAt string
	UpdatedAt string
}

func (q *Queries) CreateGroup(ctx context.Context, arg CreateGroupParams) (Group, error) {
	row := q.db.QueryRowContext(ctx, createGroup,
		arg.ID,
		arg.Name,
		arg.ParentID,
		arg.Ord,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ParentID,
		&i.Ord,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteGroup = `-- name: DeleteGroup :exec
DELETE FROM groups WHERE id = ?
`

func (q *Queries) DeleteGroup(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteGroup, id)
	return err
}

const getGroup = `-- name: GetGroup :one
SELECT id, name, parent_id, ord, created_at, updated_at FROM groups WHERE id = ?
`

func (q *Queries) GetGroup(ctx context.Context, id string) (Group, error) {
	row := q.db.QueryRowContext(ctx, getGroup, id)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ParentID,
		&i.Ord,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listGroups = `-- name: ListGroups :many
SELECT id, name, parent_id, ord, created_at, updated_at FROM groups ORDER BY ord, created_at
`

func (q *Queries) ListGroups(ctx context.Context) ([]Group, error) {
	rows, err := q.db.QueryContext(ctx, listGroups)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Group
	for rows.Next() {
		var i Group
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ParentID,
			&i.Ord,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateGroup = `-- name: UpdateGroup :one
UPDATE groups
SET name = ?, parent_id = ?, ord = ?, updated_at = ?
WHERE id = ?
RETURNING id, name, parent_id, ord, created_at, updated_at
`

type UpdateGroupParams struct {
	Name      string
	ParentID  sql.NullString
	Ord       string
	UpdatedAt string
	ID        string
}

func (q *Queries) UpdateGroup(ctx context.Context, arg UpdateGroupParams) (Group, error) {
	row := q.db.QueryRowContext(ctx, updateGroup,
		arg.Name,
		arg.ParentID,
		arg.Ord,
		arg.UpdatedAt,
		arg.ID,
	)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ParentID,
		&i.Ord,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
