// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"database/sql"
)

type Activity struct {
	ID        string
	NodeID    string
	Actor     string
	Kind      string
	Data      string
	CreatedAt string
}

type Node struct {
	ID          string
	WorkspaceID string
	Seq         int64
	Key         string
	ParentID    sql.NullString
	Kind        sql.NullString
	Title       string
	Body        string
	Ord         string
	CreatedAt   string
	UpdatedAt   string
	Origin      string
	ProposedBy  string
	SourceWs    string
}

type NodeTag struct {
	NodeID string
	TagID  string
}

type Ref struct {
	ID        string
	FromNode  string
	ToNode    string
	Kind      string
	CreatedAt string
}

type Revision struct {
	ID        string
	NodeID    string
	Snapshot  string
	Meta      string
	CreatedAt string
}

type Tag struct {
	ID          string
	WorkspaceID string
	Name        string
	CreatedAt   string
}

type Workspace struct {
	ID          string
	Key         string
	Name        string
	Description string
	NodeSeq     int64
	CreatedAt   string
	UpdatedAt   string
}
