// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: nodes.sql

package store

import (
	"context"
	"database/sql"
)

const acceptProposalNode = `-- name: AcceptProposalNode :one
UPDATE nodes SET parent_id = ?, origin = 'native', updated_at = ? WHERE id = ?
RETURNING id, workspace_id, seq, "key", parent_id, kind, title, body, ord, created_at, updated_at, origin, proposed_by, source_ws
`

type AcceptProposalNodeParams struct {
	ParentID  sql.NullString
	UpdatedAt string
	ID        string
}

// Accept a proposal into the roadmap: flip origin to native and set the parent the receiving
// architect chose. Stable key is preserved (inbound references stay valid).
func (q *Queries) AcceptProposalNode(ctx context.Context, arg AcceptProposalNodeParams) (Node, error) {
	row := q.db.QueryRowContext(ctx, acceptProposalNode, arg.ParentID, arg.UpdatedAt, arg.ID)
	var i Node
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Seq,
		&i.Key,
		&i.ParentID,
		&i.Kind,
		&i.Title,
		&i.Body,
		&i.Ord,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Origin,
		&i.ProposedBy,
		&i.SourceWs,
	)
	return i, err
}

const countChildren = `-- name: CountChildren :one
SELECT COUNT(*) FROM nodes WHERE parent_id = ?
`

func (q *Queries) CountChildren(ctx context.Context, parentID sql.NullString) (int64, error) {
	row := q.db.QueryRowContext(ctx, countChildren, parentID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createNode = `-- name: CreateNode :one
INSERT INTO nodes (id, workspace_id, seq, key, parent_id, kind, title, body, ord, origin, proposed_by, source_ws, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, workspace_id, seq, "key", parent_id, kind, title, body, ord, created_at, updated_at, origin, proposed_by, source_ws
`

type CreateNodeParams struct {
	ID          string
	WorkspaceID string
	Seq         int64
	Key         string
	ParentID    sql.NullString
	Kind        sql.NullString
	Title       string
	Body        string
	Ord         string
	Origin      string
	ProposedBy  string
	SourceWs    string
	CreatedAt   string
	UpdatedAt   string
}

func (q *Queries) CreateNode(ctx context.Context, arg CreateNodeParams) (Node, error) {
	row := q.db.QueryRowContext(ctx, createNode,
		arg.ID,
		arg.WorkspaceID,
		arg.Seq,
		arg.Key,
		arg.ParentID,
		arg.Kind,
		arg.Title,
		arg.Body,
		arg.Ord,
		arg.Origin,
		arg.ProposedBy,
		arg.SourceWs,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Node
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Seq,
		&i.Key,
		&i.ParentID,
		&i.Kind,
		&i.Title,
		&i.Body,
		&i.Ord,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Origin,
		&i.ProposedBy,
		&i.SourceWs,
	)
	return i, err
}

const declineProposalNode = `-- name: DeclineProposalNode :one
UPDATE nodes SET origin = 'declined', updated_at = ? WHERE id = ?
RETURNING id, workspace_id, seq, "key", parent_id, kind, title, body, ord, created_at, updated_at, origin, proposed_by, source_ws
`

type DeclineProposalNodeParams struct {
	UpdatedAt string
	ID        string
}

// Decline a proposal: origin -> 'declined' (terminal; out of inbox and roadmap, kept as history).
func (q *Queries) DeclineProposalNode(ctx context.Context, arg DeclineProposalNodeParams) (Node, error) {
	row := q.db.QueryRowContext(ctx, declineProposalNode, arg.UpdatedAt, arg.ID)
	var i Node
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Seq,
		&i.Key,
		&i.ParentID,
		&i.Kind,
		&i.Title,
		&i.Body,
		&i.Ord,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Origin,
		&i.ProposedBy,
		&i.SourceWs,
	)
	return i, err
}

const deleteNode = `-- name: DeleteNode :exec
DELETE FROM nodes WHERE id = ?
`

func (q *Queries) DeleteNode(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteNode, id)
	return err
}

const getNodeByID = `-- name: GetNodeByID :one
SELECT id, workspace_id, seq, "key", parent_id, kind, title, body, ord, created_at, updated_at, origin, proposed_by, source_ws FROM nodes WHERE id = ?
`

func (q *Queries) GetNodeByID(ctx context.Context, id string) (Node, error) {
	row := q.db.QueryRowContext(ctx, getNodeByID, id)
	var i Node
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Seq,
		&i.Key,
		&i.ParentID,
		&i.Kind,
		&i.Title,
		&i.Body,
		&i.Ord,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Origin,
		&i.ProposedBy,
		&i.SourceWs,
	)
	return i, err
}

const getNodeByKey = `-- name: GetNodeByKey :one
SELECT id, workspace_id, seq, "key", parent_id, kind, title, body, ord, created_at, updated_at, origin, proposed_by, source_ws FROM nodes WHERE key = ?
`

func (q *Queries) GetNodeByKey(ctx context.Context, key string) (Node, error) {
	row := q.db.QueryRowContext(ctx, getNodeByKey, key)
	var i Node
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Seq,
		&i.Key,
		&i.ParentID,
		&i.Kind,
		&i.Title,
		&i.Body,
		&i.Ord,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Origin,
		&i.ProposedBy,
		&i.SourceWs,
	)
	return i, err
}

const listChildren = `-- name: ListChildren :many
SELECT id, workspace_id, seq, "key", parent_id, kind, title, body, ord, created_at, updated_at, origin, proposed_by, source_ws FROM nodes WHERE parent_id = ? ORDER BY ord, seq
`

func (q *Queries) ListChildren(ctx context.Context, parentID sql.NullString) ([]Node, error) {
	rows, err := q.db.QueryContext(ctx, listChildren, parentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Node
	for rows.Next() {
		var i Node
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Seq,
			&i.Key,
			&i.ParentID,
			&i.Kind,
			&i.Title,
			&i.Body,
			&i.Ord,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Origin,
			&i.ProposedBy,
			&i.SourceWs,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInboxNodes = `-- name: ListInboxNodes :many
SELECT id, workspace_id, seq, "key", parent_id, kind, title, body, ord, created_at, updated_at, origin, proposed_by, source_ws FROM nodes WHERE workspace_id = ? AND origin = 'proposal' ORDER BY seq
`

// Inbox: pending cross-product proposals of a workspace, awaiting accept/decline.
func (q *Queries) ListInboxNodes(ctx context.Context, workspaceID string) ([]Node, error) {
	rows, err := q.db.QueryContext(ctx, listInboxNodes, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Node
	for rows.Next() {
		var i Node
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Seq,
			&i.Key,
			&i.ParentID,
			&i.Kind,
			&i.Title,
			&i.Body,
			&i.Ord,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Origin,
			&i.ProposedBy,
			&i.SourceWs,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNodesByWorkspace = `-- name: ListNodesByWorkspace :many
SELECT id, workspace_id, seq, "key", parent_id, kind, title, body, ord, created_at, updated_at, origin, proposed_by, source_ws FROM nodes WHERE workspace_id = ? AND origin = 'native' ORDER BY ord, seq
`

// Flat list of a workspace's roadmap nodes (origin='native' -- proposals/declined live outside
// the roadmap). Ordered by the fractional index then seq. parent filter applied in-memory.
func (q *Queries) ListNodesByWorkspace(ctx context.Context, workspaceID string) ([]Node, error) {
	rows, err := q.db.QueryContext(ctx, listNodesByWorkspace, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Node
	for rows.Next() {
		var i Node
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Seq,
			&i.Key,
			&i.ParentID,
			&i.Kind,
			&i.Title,
			&i.Body,
			&i.Ord,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Origin,
			&i.ProposedBy,
			&i.SourceWs,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRootNodes = `-- name: ListRootNodes :many
SELECT id, workspace_id, seq, "key", parent_id, kind, title, body, ord, created_at, updated_at, origin, proposed_by, source_ws FROM nodes WHERE workspace_id = ? AND parent_id IS NULL AND origin = 'native' ORDER BY ord, seq
`

// Tree roots of a workspace (top level: no parent). Excludes un-accepted proposals (they are
// parent-less like roots but must not surface in the roadmap until accepted).
func (q *Queries) ListRootNodes(ctx context.Context, workspaceID string) ([]Node, error) {
	rows, err := q.db.QueryContext(ctx, listRootNodes, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Node
	for rows.Next() {
		var i Node
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Seq,
			&i.Key,
			&i.ParentID,
			&i.Kind,
			&i.Title,
			&i.Body,
			&i.Ord,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Origin,
			&i.ProposedBy,
			&i.SourceWs,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateNode = `-- name: UpdateNode :one
UPDATE nodes
SET kind = ?, title = ?, body = ?, ord = ?, parent_id = ?, updated_at = ?
WHERE id = ?
RETURNING id, workspace_id, seq, "key", parent_id, kind, title, body, ord, created_at, updated_at, origin, proposed_by, source_ws
`

type UpdateNodeParams struct {
	Kind      sql.NullString
	Title     string
	Body      string
	Ord       string
	ParentID  sql.NullString
	UpdatedAt string
	ID        string
}

func (q *Queries) UpdateNode(ctx context.Context, arg UpdateNodeParams) (Node, error) {
	row := q.db.QueryRowContext(ctx, updateNode,
		arg.Kind,
		arg.Title,
		arg.Body,
		arg.Ord,
		arg.ParentID,
		arg.UpdatedAt,
		arg.ID,
	)
	var i Node
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Seq,
		&i.Key,
		&i.ParentID,
		&i.Kind,
		&i.Title,
		&i.Body,
		&i.Ord,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Origin,
		&i.ProposedBy,
		&i.SourceWs,
	)
	return i, err
}
