// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: refs.sql

package store

import (
	"context"
)

const createRef = `-- name: CreateRef :one
INSERT INTO refs (id, from_node, to_node, kind, created_at)
VALUES (?, ?, ?, ?, ?)
RETURNING id, from_node, to_node, kind, created_at
`

type CreateRefParams struct {
	ID        string
	FromNode  string
	ToNode    string
	Kind      string
	CreatedAt string
}

func (q *Queries) CreateRef(ctx context.Context, arg CreateRefParams) (Ref, error) {
	row := q.db.QueryRowContext(ctx, createRef,
		arg.ID,
		arg.FromNode,
		arg.ToNode,
		arg.Kind,
		arg.CreatedAt,
	)
	var i Ref
	err := row.Scan(
		&i.ID,
		&i.FromNode,
		&i.ToNode,
		&i.Kind,
		&i.CreatedAt,
	)
	return i, err
}

const deleteRef = `-- name: DeleteRef :exec
DELETE FROM refs WHERE id = ?
`

func (q *Queries) DeleteRef(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteRef, id)
	return err
}

const listBacklinks = `-- name: ListBacklinks :many
SELECT id, from_node, to_node, kind, created_at FROM refs WHERE to_node = ? ORDER BY created_at, id
`

// Backlinks: incoming edges (who points at this node) -- the DERIVED reverse query
// over to_node, served by idx_refs_to (no duplicated backlink table).
func (q *Queries) ListBacklinks(ctx context.Context, toNode string) ([]Ref, error) {
	rows, err := q.db.QueryContext(ctx, listBacklinks, toNode)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Ref
	for rows.Next() {
		var i Ref
		if err := rows.Scan(
			&i.ID,
			&i.FromNode,
			&i.ToNode,
			&i.Kind,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRefsFrom = `-- name: ListRefsFrom :many
SELECT id, from_node, to_node, kind, created_at FROM refs WHERE from_node = ? ORDER BY created_at, id
`

// Forward edges out of a node (its outgoing links/relations).
func (q *Queries) ListRefsFrom(ctx context.Context, fromNode string) ([]Ref, error) {
	rows, err := q.db.QueryContext(ctx, listRefsFrom, fromNode)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Ref
	for rows.Next() {
		var i Ref
		if err := rows.Scan(
			&i.ID,
			&i.FromNode,
			&i.ToNode,
			&i.Kind,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
