// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: revisions.sql

package store

import (
	"context"
)

const createRevision = `-- name: CreateRevision :one
INSERT INTO revisions (id, node_id, snapshot, meta, created_at)
VALUES (?, ?, ?, ?, ?)
RETURNING id, node_id, snapshot, meta, created_at
`

type CreateRevisionParams struct {
	ID        string
	NodeID    string
	Snapshot  string
	Meta      string
	CreatedAt string
}

func (q *Queries) CreateRevision(ctx context.Context, arg CreateRevisionParams) (Revision, error) {
	row := q.db.QueryRowContext(ctx, createRevision,
		arg.ID,
		arg.NodeID,
		arg.Snapshot,
		arg.Meta,
		arg.CreatedAt,
	)
	var i Revision
	err := row.Scan(
		&i.ID,
		&i.NodeID,
		&i.Snapshot,
		&i.Meta,
		&i.CreatedAt,
	)
	return i, err
}

const deleteRevisionsForNode = `-- name: DeleteRevisionsForNode :exec
DELETE FROM revisions WHERE node_id = ?
`

// All revisions of a node -- cleaned when the node is deleted.
func (q *Queries) DeleteRevisionsForNode(ctx context.Context, nodeID string) error {
	_, err := q.db.ExecContext(ctx, deleteRevisionsForNode, nodeID)
	return err
}

const getRevision = `-- name: GetRevision :one
SELECT id, node_id, snapshot, meta, created_at FROM revisions WHERE id = ?
`

func (q *Queries) GetRevision(ctx context.Context, id string) (Revision, error) {
	row := q.db.QueryRowContext(ctx, getRevision, id)
	var i Revision
	err := row.Scan(
		&i.ID,
		&i.NodeID,
		&i.Snapshot,
		&i.Meta,
		&i.CreatedAt,
	)
	return i, err
}

const listRevisions = `-- name: ListRevisions :many
SELECT id, node_id, snapshot, meta, created_at FROM revisions WHERE node_id = ? ORDER BY created_at DESC, id DESC
`

// Version history of a node, newest first.
func (q *Queries) ListRevisions(ctx context.Context, nodeID string) ([]Revision, error) {
	rows, err := q.db.QueryContext(ctx, listRevisions, nodeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Revision
	for rows.Next() {
		var i Revision
		if err := rows.Scan(
			&i.ID,
			&i.NodeID,
			&i.Snapshot,
			&i.Meta,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
