// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tags.sql

package store

import (
	"context"
)

const addNodeTag = `-- name: AddNodeTag :exec
INSERT INTO node_tags (node_id, tag_id) VALUES (?, ?)
`

type AddNodeTagParams struct {
	NodeID string
	TagID  string
}

func (q *Queries) AddNodeTag(ctx context.Context, arg AddNodeTagParams) error {
	_, err := q.db.ExecContext(ctx, addNodeTag, arg.NodeID, arg.TagID)
	return err
}

const createTag = `-- name: CreateTag :one
INSERT INTO tags (id, workspace_id, name, created_at)
VALUES (?, ?, ?, ?)
RETURNING id, workspace_id, name, created_at
`

type CreateTagParams struct {
	ID          string
	WorkspaceID string
	Name        string
	CreatedAt   string
}

func (q *Queries) CreateTag(ctx context.Context, arg CreateTagParams) (Tag, error) {
	row := q.db.QueryRowContext(ctx, createTag,
		arg.ID,
		arg.WorkspaceID,
		arg.Name,
		arg.CreatedAt,
	)
	var i Tag
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const getTag = `-- name: GetTag :one
SELECT id, workspace_id, name, created_at FROM tags WHERE id = ?
`

func (q *Queries) GetTag(ctx context.Context, id string) (Tag, error) {
	row := q.db.QueryRowContext(ctx, getTag, id)
	var i Tag
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const listNodeTags = `-- name: ListNodeTags :many
SELECT t.id, t.workspace_id, t.name, t.created_at FROM tags t
JOIN node_tags nt ON nt.tag_id = t.id
WHERE nt.node_id = ?
ORDER BY t.name
`

// Tags applied to a node (join across the m2m).
func (q *Queries) ListNodeTags(ctx context.Context, nodeID string) ([]Tag, error) {
	rows, err := q.db.QueryContext(ctx, listNodeTags, nodeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tag
	for rows.Next() {
		var i Tag
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Name,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTagsByWorkspace = `-- name: ListTagsByWorkspace :many
SELECT id, workspace_id, name, created_at FROM tags WHERE workspace_id = ? ORDER BY name
`

func (q *Queries) ListTagsByWorkspace(ctx context.Context, workspaceID string) ([]Tag, error) {
	rows, err := q.db.QueryContext(ctx, listTagsByWorkspace, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tag
	for rows.Next() {
		var i Tag
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Name,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeNodeTag = `-- name: RemoveNodeTag :exec
DELETE FROM node_tags WHERE node_id = ? AND tag_id = ?
`

type RemoveNodeTagParams struct {
	NodeID string
	TagID  string
}

func (q *Queries) RemoveNodeTag(ctx context.Context, arg RemoveNodeTagParams) error {
	_, err := q.db.ExecContext(ctx, removeNodeTag, arg.NodeID, arg.TagID)
	return err
}
